# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TV Guide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TV Guide
  pod 'R.swift', '6.1.0'

  target 'TV GuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TV GuideUITests' do
    # Pods for testing
  end

end
